# Assignment Day 15

Question 1:Create a 3x3x3 array with random values.

In [139]:
import numpy as np

In [140]:
x = np.random.random((3,3,3))

In [141]:
x

array([[[0.22465047, 0.93808005, 0.51244905],
        [0.67237287, 0.15185651, 0.38827574],
        [0.1197788 , 0.48967503, 0.70451466]],

       [[0.40272949, 0.87059694, 0.16886373],
        [0.37264419, 0.5445896 , 0.07549875],
        [0.49512914, 0.35337842, 0.91287057]],

       [[0.8378749 , 0.93650667, 0.79128188],
        [0.90083216, 0.23764637, 0.46346016],
        [0.86079554, 0.96248786, 0.76526989]]])

Question 2:Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [142]:
y = np.diag(1 + np.arange(4),k = -1)

In [143]:
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


Question 3:Create a 8x8 matrix and fill it with a checkerboard pattern

In [144]:
z = np.ones((8,8), dtype = int)

In [145]:
z[1::2, ::2]= 0

In [146]:
z[::2, 1::2] = 0

In [147]:
print(z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


Question 4:Normalize a 5x5 random matrix

In [148]:
a = np.random.random((5,5))

In [149]:
print(a)

[[0.65427637 0.45963472 0.7313908  0.76255517 0.48283757]
 [0.40712645 0.57957545 0.32926833 0.28011719 0.96260422]
 [0.01140664 0.31586992 0.7999704  0.14692211 0.81008078]
 [0.88911387 0.50221082 0.69260899 0.66629599 0.71952756]
 [0.81476476 0.20514844 0.50759016 0.7732694  0.17736603]]


In [150]:
a = (a - a.min())/(a.max() - a.min())

In [151]:
print(a)

[[0.675853   0.471225   0.75692388 0.78968718 0.49561831]
 [0.41602273 0.59731945 0.33417    0.28249709 1.        ]
 [0.         0.32008416 0.82902205 0.14246826 0.83965115]
 [0.92273914 0.51598553 0.71615232 0.6884893  0.74445199]
 [0.84457545 0.20368197 0.52164085 0.80095112 0.17447415]]


Question 5:How to find common values between two arrays?

In [152]:
array1 = [1,2,3,4,5,6]
array2 = [2,3,7,8,9]
print("The value common in both the arrays are:",np.intersect1d(array1,array2))

The value common in both the arrays are: [2 3]


Question 6:How to get the dates of yesterday, today and tomorrow?

In [153]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D')  + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


Question 7:Consider two random array A and B, check if they are equal

In [154]:
p = np.random.randint(1,3,4)
q = np.random.randint(1,3,4)

b = np.allclose(p,q)
print(b)


False


Question 8:Create random vector of size 10 and replace the maximum value by 0

In [155]:
x = np.random.random(10)

In [156]:
x[x.argmax()]=10
x

array([ 0.33770593,  0.80348234,  0.58753808,  0.49049994,  0.17051205,
        0.22245268, 10.        ,  0.96671751,  0.13760692,  0.53852974])

Question 9: How to print all the values of an array?

In [157]:
Z = np.zeros((5,5))
print(Z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Question 10:Subtract the mean of each row of a matrix

In [158]:
w = np.random.rand(1,10)
z = w - w.mean(axis = 1,keepdims = True)
print(z)

[[ 0.1066742   0.10016655  0.15604789 -0.02246282  0.02683774 -0.03680156
   0.09041837 -0.14493437  0.01946457 -0.29541056]]


Question 11:Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [160]:
p = np.ones(10)
q = np.random.randint(0,len(p),20)
p += np.bincount(q, minlength=len(p))
print(p)

[3. 4. 3. 2. 2. 4. 3. 3. 2. 4.]


Question 12:How to get the diagonal of a dot product?

In [161]:
p = np.random.randint(0,5,(3,3))
q= np.random.randint(0,5,(3,3))

np.diag(np.dot(p, q))

array([ 6, 20, 28])

Question 13:How to find the most frequent value in an array?

In [162]:
c = [1,2,3,2,3,1,4,3,6,2,4,2,4,3]
d = np.array(c)
print("The most frequent value in the array is",np.bincount(d).argmax())

The most frequent value in the array is 2


Question 14:How to get the n largest values of an array

In [163]:
a = np.array([1, 3, 4, 2, 2,2])
n=3
v=a[np.argsort(a)]
print(v[-n:])

[2 3 4]


Question 15:How to create a record array from a regular array?

In [164]:
import numpy as np
arra1 = np.array([("Saurav", 90, 90),
                 ("Suraj", 90, 93),
             ("Shashwat", 91.5, 91)])
print("Regular arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='name, marks1, marks2')
print(result)

Regular arrays:
[['Saurav' '90' '90']
 ['Suraj' '90' '93']
 ['Shashwat' '91.5' '91']]

Record array;
[('Saurav', '90', '90') ('Suraj', '90', '93') ('Shashwat', '91.5', '91')]
